// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0hAobnh8JmHamhmSr1fsGp9A_T-3gfN8',
    appId: '1:679715313540:web:a84870737bf484da0a6fd1',
    messagingSenderId: '679715313540',
    projectId: 'rfks-ttm',
    authDomain: 'rfks-ttm.firebaseapp.com',
    storageBucket: 'rfks-ttm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCo_MkBHqBFT_3Ghqr-nNRFOs3iXid0fM',
    appId: '1:679715313540:android:2b1c8acc4adde7ea0a6fd1',
    messagingSenderId: '679715313540',
    projectId: 'rfks-ttm',
    storageBucket: 'rfks-ttm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-pOR3Q27HnbxkDzbdkX2RgkQq4O9OJ8',
    appId: '1:679715313540:ios:5bea6d24b9a215820a6fd1',
    messagingSenderId: '679715313540',
    projectId: 'rfks-ttm',
    storageBucket: 'rfks-ttm.appspot.com',
    iosClientId: '679715313540-4026j42ckpjdo7uf92hgivqa7d3ubb34.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttm',
  );
}
